# FROM maven:3.9.3 AS build
# WORKDIR /app
# ARG CONTAINER_PORT
# COPY pom.xml /app
# RUN mvn dependency:resolve
# COPY . /app
# RUN mvn clean
# RUN mvn package -DskipTest -x
#
# FROM openjdk:20
# COPY
