# DataBase

  MYSQL_USERNAME: root
  MYSQL_PASSWORD: 123456
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  MYSQL_DATABASE: backio

  #ServerConfiguration
  CONTAINER_PORT: 8080
  ACTIVE_PROFILE: dev

  #Secret
  JWT_SECRET: mySuperComplexSecret

